/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package converter;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author JOHN
 */
public class currency extends javax.swing.JFrame {

    /**
     * Creates new form currency
     */
    public currency() {
        initComponents();
        
         Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txt_currency_display = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        txt_currency = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(210, 410, 90, 30);

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(400, 410, 90, 30);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("Convert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(290, 300, 120, 40);

        txt_currency_display.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txt_currency_display.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel1.add(txt_currency_display);
        txt_currency_display.setBounds(400, 150, 160, 40);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Currency Converter");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 20, 700, 60);

        jComboBox1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dollar", "Taka", "Euro", "Rupee" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(130, 210, 160, 40);

        jComboBox2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Euro", "Dollar", "Taka", "Rupee" }));
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(400, 210, 160, 40);

        txt_currency.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        txt_currency.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel1.add(txt_currency);
        txt_currency.setBounds(130, 150, 160, 40);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("=");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(290, 150, 110, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/converter/backC.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 700, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
       double currency = Double.parseDouble(txt_currency.getText());

        if (jComboBox1.getSelectedItem().equals("Dollar")) {

            if (jComboBox2.getSelectedItem().equals("Taka")) {
                String cConvert1 = String.format("%.2f", currency * 80.94);
                txt_currency_display.setText(cConvert1);
            }
            
            if (jComboBox2.getSelectedItem().equals("Euro")) {
                String cConvert2 = String.format("%.2f", currency * 0.85);
                txt_currency_display.setText(cConvert2);
            }
            
            if (jComboBox2.getSelectedItem().equals("Rupee")) {
                String cConvert3 = String.format("%.2f", currency * 64.11);
                txt_currency_display.setText(cConvert3);
            }
        }
        
        if (jComboBox1.getSelectedItem().equals("Taka")) {

            if (jComboBox2.getSelectedItem().equals("Dollar")) {
                String cConvert1 = String.format("%.2f", currency * 0.012);
                txt_currency_display.setText(cConvert1);
            }
            
            if (jComboBox2.getSelectedItem().equals("Euro")) {
                String cConvert2 = String.format("%.2f", currency * 0.0105);
                txt_currency_display.setText(cConvert2);
            }
            
            if (jComboBox2.getSelectedItem().equals("Rupee")) {
                String cConvert3 = String.format("%.2f", currency * 0.79);
                txt_currency_display.setText(cConvert3);
            }
        }
        
        if (jComboBox1.getSelectedItem().equals("Euro")) {

            if (jComboBox2.getSelectedItem().equals("Dollar")) {
                String cConvert1 = String.format("%.2f", currency * 1.18);
                txt_currency_display.setText(cConvert1);
            }
            
            if (jComboBox2.getSelectedItem().equals("Taka")) {
                String cConvert2 = String.format("%.2f", currency * 95.12);
                txt_currency_display.setText(cConvert2);
            }
            
            if (jComboBox2.getSelectedItem().equals("Rupee")) {
                String cConvert3 = String.format("%.2f", currency * 75.49);
                txt_currency_display.setText(cConvert3);
            }
        }
        
        if (jComboBox1.getSelectedItem().equals("Rupee")) {

            if (jComboBox2.getSelectedItem().equals("Dollar")) {
                String cConvert1 = String.format("%.2f", currency * 0.016);
                txt_currency_display.setText(cConvert1);
            }
            
            if (jComboBox2.getSelectedItem().equals("Taka")) {
                String cConvert2 = String.format("%.2f", currency * 1.26);
                txt_currency_display.setText(cConvert2);
            }
            
            if (jComboBox2.getSelectedItem().equals("Euro")) {
                String cConvert3 = String.format("%.2f", currency * 0.013);
                txt_currency_display.setText(cConvert3);
            }
        }
       
       
       
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        manupage p = new manupage();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        txt_currency.setText(null);
        txt_currency_display.setText(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(currency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(currency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(currency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(currency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new currency().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_currency;
    private javax.swing.JTextField txt_currency_display;
    // End of variables declaration//GEN-END:variables
}
